"""
CrewAI Simple Agent System
=========================

This module demonstrates a basic single-agent system using CrewAI framework with OpenAI's GPT-5 model.
The system uses a single Research Analyst agent to perform AI trend analysis.

This is a simplified version of the multi-agent system, useful for:
- Learning CrewAI basics
- Testing single-agent workflows
- Prototyping agent behaviors

Dependencies:
- crewai: Framework for orchestrating role-playing, autonomous AI agents
- OpenAI GPT-5: Large language model provider

Author: Tayyab
Date: September 2025
"""

from crewai import Agent, Task, Crew, Process, LLM

# =============================================================================
# Configuration and Setup
# =============================================================================

# Initialize the Large Language Model (LLM) with GPT-5
# Note: This assumes GPT-5 is available and you have proper OpenAI API credentials
# Make sure to set OPENAI_API_KEY in your environment variables
llm = LLM(model="gpt-5")  # OpenAI's most advanced model

# =============================================================================
# Agent Definition
# =============================================================================

# Research Analyst Agent
# This is a single-purpose agent focused solely on research and analysis
researcher = Agent(
    role='Research Analyst',                           # Primary role/identity of the agent
    goal='Analyze and research topics thoroughly',     # Primary objective
    backstory=(
        'You are an experienced research analyst with deep expertise in '
        'technology trends, market analysis, and data synthesis. You excel '
        'at breaking down complex topics into digestible insights and '
        'identifying key patterns and future implications.'
    ),
    verbose=True,                                      # Enable detailed logging
    allow_delegation=False,                            # Prevent this agent from delegating tasks
    llm=llm                                           # Assign the configured LLM
)

# =============================================================================
# Task Definition
# =============================================================================

# Research Task
# This task instructs the agent to perform comprehensive AI trend analysis
research_task = Task(
    description=(
        'Research the latest trends in artificial intelligence and provide a comprehensive summary. '
        'Your analysis should cover emerging technologies, breakthrough developments, key market '
        'players, adoption patterns across industries, and potential future implications. '
        'Focus on actionable insights and significant developments from the past year.'
    ),
    agent=researcher,                                  # Assign to the researcher agent
    expected_output=(
        'A detailed report on AI trends including key developments, market insights, '
        'and future predictions. The report should be concise but comprehensive, '
        'maximum 100 words, highlighting the most significant trends and their '
        'potential impact on businesses and society.'
    )
)

# =============================================================================
# Crew Configuration
# =============================================================================

# Create a single-agent crew
# Even with one agent, CrewAI provides useful orchestration and logging capabilities
crew = Crew(
    agents=[researcher],                               # Single agent in the crew
    tasks=[research_task],                            # Single task to be executed
    process=Process.sequential,                        # Process type (sequential by default)
    verbose=True                                       # Enable detailed logging
)

# =============================================================================
# Main Execution Block
# =============================================================================

def main():
    """
    Main execution function for the single-agent research workflow.

    This function demonstrates the basic CrewAI execution pattern:
    1. Initialize the crew with agent(s) and task(s)
    2. Execute the workflow using crew.kickoff()
    3. Process and display the results

    Returns:
        str: The research report generated by the agent
    """
    print("🔍 Starting CrewAI Single-Agent Research System...")
    print("📊 Task: AI Trends Analysis")
    print("-" * 50)

    try:
        # Execute the crew and get results
        # The kickoff() method initiates the execution of all assigned tasks
        result = crew.kickoff()

        # Display the research results with formatting
        print("\n" + "="*50)
        print("📋 RESEARCH RESULTS")
        print("="*50)
        print(result)
        print("="*50)
        print("✅ Research task completed successfully!")

        return result

    except Exception as e:
        print(f"❌ Error during research execution: {str(e)}")
        print("💡 Tip: Make sure your OpenAI API key is properly configured")
        raise

# Execute only when run directly (not when imported as a module)
if __name__ == "__main__":
    main()
